package mcpserver

import (
	"context"
	"encoding/json"
	"fmt"
	"path/filepath"
	"time"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/ulaista/usage-ai-on-dev/internal/autotune"
	contextpkg "github.com/ulaista/usage-ai-on-dev/internal/context"
	"github.com/ulaista/usage-ai-on-dev/internal/core"
	"github.com/ulaista/usage-ai-on-dev/internal/developerflow"
	"github.com/ulaista/usage-ai-on-dev/internal/domain"
	"github.com/ulaista/usage-ai-on-dev/internal/hardware"
	"github.com/ulaista/usage-ai-on-dev/internal/localworker"
	"github.com/ulaista/usage-ai-on-dev/internal/projectmode"
	"github.com/ulaista/usage-ai-on-dev/internal/repomap"
	"github.com/ulaista/usage-ai-on-dev/internal/router"
	"github.com/ulaista/usage-ai-on-dev/internal/verification"
)

func text(v any) (*mcp.CallToolResult, any, error) {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil { return nil,nil,err }
	return &mcp.CallToolResult{Content:[]mcp.Content{&mcp.TextContent{Text:string(data)}}},v,nil
}

func New(svc *core.Service) *mcp.Server {
	server:=mcp.NewServer(&mcp.Implementation{Name:"project-brain",Version:"v0.10.0"},nil)
	type emptyArgs struct{}
	mcp.AddTool(server,&mcp.Tool{Name:"brain_status",Description:"Return Project Brain status, project mode, hardware, semantic lifecycle and token economy."},func(ctx context.Context,_ *mcp.CallToolRequest,_ emptyArgs)(*mcp.CallToolResult,any,error){status,err:=svc.Status(ctx);if err!=nil{return nil,nil,err};if project,err:=(projectmode.Engine{Root:svc.Config.Root,StateDir:svc.Config.StateDir}).Detect(ctx);err==nil{status["project"]=project};if view,err:=hardware.Review(ctx,svc.Config.StateDir);err==nil{status["hardware_policy"]=view};if report,err:=autotune.LoadReport(autotune.ReportPath(svc.Config.StateDir));err==nil{status["autotune_recommendation"]=report.Recommendation};return text(status)})
	mcp.AddTool(server,&mcp.Tool{Name:"brain_economy",Description:"Return cache, deduplication and estimated context-token savings."},func(ctx context.Context,_ *mcp.CallToolRequest,_ emptyArgs)(*mcp.CallToolResult,any,error){stats,err:=svc.Store.EconomySummary(ctx);if err!=nil{return nil,nil,err};return text(stats)})

	mcp.AddTool(server,&mcp.Tool{Name:"brain_project_detect",Description:"Detect whether this is a new or existing project and mechanically discover language, build, tests, CI and dirty worktree."},func(ctx context.Context,_ *mcp.CallToolRequest,_ emptyArgs)(*mcp.CallToolResult,any,error){project,err:=(projectmode.Engine{Root:svc.Config.Root,StateDir:svc.Config.StateDir}).Detect(ctx);if err!=nil{return nil,nil,err};return text(project)})
	type projectBeginArgs struct{SessionID string `json:"session_id"`;Task string `json:"task"`}
	mcp.AddTool(server,&mcp.Tool{Name:"brain_project_begin",Description:"Capture an immutable developer-task baseline, including pre-existing USER_DIRTY files, before modifying an existing project."},func(ctx context.Context,_ *mcp.CallToolRequest,args projectBeginArgs)(*mcp.CallToolResult,any,error){if args.SessionID==""||args.Task==""{return nil,nil,fmt.Errorf("session_id and task are required")};b,err:=(projectmode.Engine{Root:svc.Config.Root,StateDir:svc.Config.StateDir}).Begin(ctx,args.SessionID,args.Task);if err!=nil{return nil,nil,err};return text(b)})
	type projectImpactArgs struct{SessionID string `json:"session_id"`}
	mcp.AddTool(server,&mcp.Tool{Name:"brain_project_impact",Description:"Analyze affected files, related tests/config, recent history, bug regression window and BASE/USER_DIRTY/BRAIN_DELTA ownership."},func(ctx context.Context,_ *mcp.CallToolRequest,args projectImpactArgs)(*mcp.CallToolResult,any,error){if args.SessionID==""{return nil,nil,fmt.Errorf("session_id is required")};impact,err:=(projectmode.Engine{Root:svc.Config.Root,StateDir:svc.Config.StateDir}).Impact(ctx,args.SessionID);if err!=nil{return nil,nil,err};return text(impact)})
	type developerFlowArgs struct{SessionID string `json:"session_id"`;Task string `json:"task"`}
	mcp.AddTool(server,&mcp.Tool{Name:"brain_developer_flow",Description:"Prepare a developer request in one pass: brownfield recovery, ownership, impact, semantic evidence, compact context, routing and planned AI-call counts."},func(ctx context.Context,_ *mcp.CallToolRequest,args developerFlowArgs)(*mcp.CallToolResult,any,error){if args.SessionID==""||args.Task==""{return nil,nil,fmt.Errorf("session_id and task are required")};plan,err:=(developerflow.Engine{Service:svc}).Prepare(ctx,args.SessionID,args.Task);if err!=nil{return nil,nil,err};return text(plan)})

	type routeArgs struct{Task string `json:"task"`;TaskType string `json:"task_type,omitempty"`;Model string `json:"model,omitempty"`;ContextTokens int `json:"context_tokens,omitempty"`;ProjectMode string `json:"project_mode,omitempty"`;DiscoveryReady bool `json:"discovery_ready,omitempty"`;CacheHit bool `json:"cache_hit,omitempty"`;SemanticOnly bool `json:"semantic_only,omitempty"`}
	mcp.AddTool(server,&mcp.Tool{Name:"brain_route",Description:"Return deterministic mechanical/local/local-verify/strong routing using risk and workload telemetry without adding an LLM call."},func(ctx context.Context,_ *mcp.CallToolRequest,args routeArgs)(*mcp.CallToolResult,any,error){d,err:=(router.Router{Stats:svc.Store}).Decide(ctx,router.Request{Task:args.Task,TaskType:args.TaskType,Model:args.Model,ContextTokens:args.ContextTokens,ProjectMode:args.ProjectMode,DiscoveryReady:args.DiscoveryReady,CacheHit:args.CacheHit,SemanticOnly:args.SemanticOnly});if err!=nil{return nil,nil,err};return text(d)})

	mcp.AddTool(server,&mcp.Tool{Name:"brain_hardware",Description:"Detect CPU, RAM, GPU/VRAM, runtime pressure and recommended/effective local-AI limits."},func(ctx context.Context,_ *mcp.CallToolRequest,_ emptyArgs)(*mcp.CallToolResult,any,error){view,err:=hardware.Review(ctx,svc.Config.StateDir);if err!=nil{return nil,nil,err};return text(view)})
	type acceptHardwareArgs struct{MemoryReserveMB int `json:"memory_reserve_mb,omitempty"`;SoftContextTokens int `json:"soft_context_tokens,omitempty"`;HardContextTokens int `json:"hard_context_tokens,omitempty"`;MaxOutputTokens int `json:"max_output_tokens,omitempty"`;MaxParallelWorkers int `json:"max_parallel_workers,omitempty"`;PreferredModel string `json:"preferred_model,omitempty"`;PreferredModelClass string `json:"preferred_model_class,omitempty"`}
	mcp.AddTool(server,&mcp.Tool{Name:"brain_hardware_accept",Description:"Accept current hardware recommendations, optionally with user overrides."},func(ctx context.Context,_ *mcp.CallToolRequest,args acceptHardwareArgs)(*mcp.CallToolResult,any,error){view,err:=hardware.Review(ctx,svc.Config.StateDir);if err!=nil{return nil,nil,err};override:=hardware.Limits{MemoryReserveMB:args.MemoryReserveMB,SoftContextTokens:args.SoftContextTokens,HardContextTokens:args.HardContextTokens,MaxOutputTokens:args.MaxOutputTokens,MaxParallelWorkers:args.MaxParallelWorkers,PreferredModel:args.PreferredModel,PreferredModelClass:args.PreferredModelClass};policy:=hardware.AcceptPolicy(view.Snapshot,override);if err:=hardware.SavePolicy(hardware.PolicyPath(svc.Config.StateDir),policy);err!=nil{return nil,nil,err};return text(hardware.BuildView(view.Snapshot,policy))})
	mcp.AddTool(server,&mcp.Tool{Name:"brain_hardware_reset",Description:"Discard accepted hardware overrides and return to automatic recommendations."},func(ctx context.Context,_ *mcp.CallToolRequest,_ emptyArgs)(*mcp.CallToolResult,any,error){if err:=hardware.ResetPolicy(hardware.PolicyPath(svc.Config.StateDir));err!=nil{return nil,nil,err};view,err:=hardware.Review(ctx,svc.Config.StateDir);if err!=nil{return nil,nil,err};return text(view)})

	type autotuneArgs struct{Models []string `json:"models,omitempty"`;Contexts []int `json:"contexts,omitempty"`;MaxModels int `json:"max_models,omitempty"`;OutputTokens int `json:"output_tokens,omitempty"`;Force bool `json:"force,omitempty"`}
	mcp.AddTool(server,&mcp.Tool{Name:"brain_autotune",Description:"Benchmark installed Ollama models, reusing identical capability results unless force=true."},func(ctx context.Context,_ *mcp.CallToolRequest,args autotuneArgs)(*mcp.CallToolResult,any,error){runner:=autotune.Runner{OllamaURL:svc.Config.OllamaURL,StateDir:svc.Config.StateDir};cached,err:=runner.RunCached(ctx,autotune.Options{Models:args.Models,Contexts:args.Contexts,MaxModels:args.MaxModels,OutputTokens:args.OutputTokens},args.Force);if err!=nil{return nil,nil,err};report:=cached.Report;if cached.Hit{in,out:=autotune.ReportTokenCost(report);_ = svc.Store.RecordSaving(ctx,domain.CacheSaving{Kind:"autotune",Key:cached.Key,SavedInputTokens:in,SavedOutputTokens:out,CreatedAt:time.Now().UTC()})};if err:=autotune.SaveReport(autotune.ReportPath(svc.Config.StateDir),report);err!=nil{return nil,nil,err};return text(map[string]any{"cache_hit":cached.Hit,"applied":false,"requires_user_acceptance":report.Recommendation.PreferredModel!="","report":report})})
	mcp.AddTool(server,&mcp.Tool{Name:"brain_autotune_show",Description:"Return latest saved capability benchmark."},func(ctx context.Context,_ *mcp.CallToolRequest,_ emptyArgs)(*mcp.CallToolResult,any,error){report,err:=autotune.LoadReport(autotune.ReportPath(svc.Config.StateDir));if err!=nil{return nil,nil,err};return text(report)})
	mcp.AddTool(server,&mcp.Tool{Name:"brain_autotune_accept",Description:"Accept latest autotune recommendation, optionally with user overrides."},func(ctx context.Context,_ *mcp.CallToolRequest,args acceptHardwareArgs)(*mcp.CallToolResult,any,error){report,err:=autotune.LoadReport(autotune.ReportPath(svc.Config.StateDir));if err!=nil{return nil,nil,err};view,err:=hardware.Review(ctx,svc.Config.StateDir);if err!=nil{return nil,nil,err};if err:=autotune.ValidateReportForHardware(report,view.Snapshot.Inventory.HardwareID);err!=nil{return nil,nil,err};override:=hardware.ApplyOverride(report.Recommendation.PolicyOverride,hardware.Limits{MemoryReserveMB:args.MemoryReserveMB,SoftContextTokens:args.SoftContextTokens,HardContextTokens:args.HardContextTokens,MaxOutputTokens:args.MaxOutputTokens,MaxParallelWorkers:args.MaxParallelWorkers,PreferredModel:args.PreferredModel,PreferredModelClass:args.PreferredModelClass});policy:=hardware.AcceptPolicy(view.Snapshot,override);if err:=hardware.SavePolicy(hardware.PolicyPath(svc.Config.StateDir),policy);err!=nil{return nil,nil,err};return text(map[string]any{"applied":true,"source":"autotune","hardware_policy":hardware.BuildView(view.Snapshot,policy),"recommendation":report.Recommendation})})

	type contextArgs struct{Task string `json:"task"`;MaxTokens int `json:"max_tokens,omitempty"`}
	mcp.AddTool(server,&mcp.Tool{Name:"brain_context",Description:"Compile or reuse a content-addressed full task context capsule."},func(ctx context.Context,_ *mcp.CallToolRequest,args contextArgs)(*mcp.CallToolResult,any,error){if args.Task==""{return nil,nil,fmt.Errorf("task is required")};cached,err:=(contextpkg.Compiler{Service:svc}).CompileCached(ctx,args.Task,args.MaxTokens);if err!=nil{return nil,nil,err};return text(map[string]any{"cache_hit":cached.Hit,"state_id":cached.StateID,"cache_key":cached.Key,"packet":cached.Packet,"markdown":cached.Packet.RenderMarkdown()})})
	type deltaArgs struct{SessionID string `json:"session_id"`;Task string `json:"task"`;MaxTokens int `json:"max_tokens,omitempty"`}
	mcp.AddTool(server,&mcp.Tool{Name:"brain_context_delta",Description:"Return full context on first session call, then only compact changes."},func(ctx context.Context,_ *mcp.CallToolRequest,args deltaArgs)(*mcp.CallToolResult,any,error){if args.SessionID==""||args.Task==""{return nil,nil,fmt.Errorf("session_id and task are required")};delta,err:=(contextpkg.Compiler{Service:svc}).CompileDelta(ctx,args.SessionID,args.Task,args.MaxTokens);if err!=nil{return nil,nil,err};return text(map[string]any{"delta":delta,"markdown":delta.RenderMarkdown()})})

	type workerArgs struct{SessionID string `json:"session_id,omitempty"`;Task string `json:"task"`;TaskType string `json:"task_type,omitempty"`;VerificationMaxTokens int `json:"verification_max_tokens,omitempty"`}
	mcp.AddTool(server,&mcp.Tool{Name:"brain_local_run",Description:"Prepare brownfield/new-project recovery, route safely, run or reuse bounded local work, and return a compact verification capsule."},func(ctx context.Context,_ *mcp.CallToolRequest,args workerArgs)(*mcp.CallToolResult,any,error){if args.Task==""{return nil,nil,fmt.Errorf("task is required")};if args.SessionID==""{args.SessionID=fmt.Sprintf("mcp-%d",time.Now().UnixNano())};plan,err:=(developerflow.Engine{Service:svc}).Prepare(ctx,args.SessionID,args.Task);if err!=nil{return nil,nil,err};view,err:=hardware.Review(ctx,svc.Config.StateDir);if err!=nil{return nil,nil,err};model:=svc.Config.LocalModel;if view.Effective.PreferredModel!=""{model=view.Effective.PreferredModel};taskType:=plan.Baseline.TaskKind;if args.TaskType!=""{taskType=args.TaskType};packet:=plan.Context.Packet;worker:=localworker.Worker{Model:model,OllamaURL:svc.Config.OllamaURL,StateDir:svc.Config.StateDir,Store:svc.Store,Limits:&view.Effective};result,err:=worker.Run(ctx,localworker.Request{Task:args.Task,TaskType:taskType,Context:packet.RenderMarkdown(),ContextTokens:packet.EstimatedTokens,ProjectMode:plan.Project.Mode,DiscoveryReady:plan.Impact.DiscoveryReady});if err!=nil{return nil,nil,err};response:=map[string]any{"developer_flow":plan,"hardware_policy":view,"result":result};capsule:=verification.Build(verification.BuildRequest{Task:args.Task,StateID:plan.Context.StateID,ContextKey:plan.Context.Key,Packet:packet,Result:result,MaxTokens:args.VerificationMaxTokens});response["verification_capsule"]=capsule;response["verification_markdown"]=capsule.RenderMarkdown();if !result.FallbackRequired&&capsule.EstimatedTokenSaving>0{_ = svc.Store.RecordSaving(ctx,domain.CacheSaving{Kind:"verification",Key:capsule.Fingerprint(),SavedInputTokens:capsule.EstimatedTokenSaving,CreatedAt:time.Now().UTC()})};return text(response)})

	type repoMapArgs struct{Task string `json:"task"`;MaxTokens int `json:"max_tokens,omitempty"`;Changed []string `json:"changed_files,omitempty"`}
	mcp.AddTool(server,&mcp.Tool{Name:"brain_repo_map",Description:"Build a compact task-ranked repository map."},func(ctx context.Context,_ *mcp.CallToolRequest,args repoMapArgs)(*mcp.CallToolResult,any,error){if args.Task==""{return nil,nil,fmt.Errorf("task is required")};budget:=args.MaxTokens;if budget<=0{budget=svc.Config.RepoMapTokens};result,err:=(repomap.Builder{Root:svc.Config.Root,CachePath:filepath.Join(svc.Config.StateDir,"cache","repomap.json"),MaxFiles:svc.Config.RepoMapMaxFiles}).Build(ctx,repomap.Request{Task:args.Task,ChangedFiles:args.Changed,TokenBudget:budget});if err!=nil{return nil,nil,err};return text(result)})
	type createIntentArgs struct{Title string `json:"title"`;Goal string `json:"goal,omitempty"`;Constraints []string `json:"constraints,omitempty"`;Affected []string `json:"affected,omitempty"`;Verification []string `json:"verification,omitempty"`}
	mcp.AddTool(server,&mcp.Tool{Name:"brain_intent_create",Description:"Create durable development intent before multi-step work."},func(ctx context.Context,_ *mcp.CallToolRequest,args createIntentArgs)(*mcp.CallToolResult,any,error){if args.Title==""{return nil,nil,fmt.Errorf("title is required")};in,err:=svc.CreateIntent(ctx,args.Title,args.Goal,args.Constraints,args.Affected,args.Verification);if err!=nil{return nil,nil,err};return text(in)})
	type batchArgs struct{IntentID string `json:"intent_id"`;Title string `json:"title"`;Scope []string `json:"scope,omitempty"`}
	mcp.AddTool(server,&mcp.Tool{Name:"brain_batch_create",Description:"Create a semantic change batch."},func(ctx context.Context,_ *mcp.CallToolRequest,args batchArgs)(*mcp.CallToolResult,any,error){if args.IntentID==""||args.Title==""{return nil,nil,fmt.Errorf("intent_id and title are required")};b,err:=svc.CreateBatch(ctx,args.IntentID,args.Title,args.Scope);if err!=nil{return nil,nil,err};return text(b)})
	mcp.AddTool(server,&mcp.Tool{Name:"brain_intent_list",Description:"List active development intents."},func(ctx context.Context,_ *mcp.CallToolRequest,_ emptyArgs)(*mcp.CallToolResult,any,error){rows,err:=svc.Store.ListActiveIntents(ctx);if err!=nil{return nil,nil,err};return text(rows)})
	type telemetryArgs struct{Model string `json:"model,omitempty"`}
	mcp.AddTool(server,&mcp.Tool{Name:"brain_telemetry",Description:"Summarize model latency, tokens, fallbacks and acceptance."},func(ctx context.Context,_ *mcp.CallToolRequest,args telemetryArgs)(*mcp.CallToolResult,any,error){stats,err:=svc.Store.TelemetrySummary(ctx,args.Model);if err!=nil{return nil,nil,err};return text(stats)})
	type symbolArgs struct{Pattern string `json:"pattern"`;RelativePath string `json:"relative_path,omitempty"`;IncludeBody bool `json:"include_body,omitempty"`;Depth int `json:"depth,omitempty"`}
	mcp.AddTool(server,&mcp.Tool{Name:"brain_find_symbol",Description:"Find code symbols through the cached semantic provider."},func(ctx context.Context,_ *mcp.CallToolRequest,args symbolArgs)(*mcp.CallToolResult,any,error){if svc.Semantic==nil{return nil,nil,fmt.Errorf("semantic provider is not connected: %s",svc.SemanticError)};result,err:=svc.Semantic.FindSymbol(ctx,domain.SymbolQuery{Pattern:args.Pattern,RelativePath:args.RelativePath,IncludeBody:args.IncludeBody,Depth:args.Depth});if err!=nil{return nil,nil,err};return text(result)})
	type refsArgs struct{NamePath string `json:"name_path"`;RelativePath string `json:"relative_path"`}
	mcp.AddTool(server,&mcp.Tool{Name:"brain_find_references",Description:"Find references using the cached semantic provider."},func(ctx context.Context,_ *mcp.CallToolRequest,args refsArgs)(*mcp.CallToolResult,any,error){if svc.Semantic==nil{return nil,nil,fmt.Errorf("semantic provider is not connected: %s",svc.SemanticError)};result,err:=svc.Semantic.FindReferences(ctx,args.NamePath,args.RelativePath);if err!=nil{return nil,nil,err};return text(result)})
	return server
}
